'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace Demo3

    Partial Public Class DonNhapHangs
        Inherits XPObject
        Dim fid_donnhaphang As String
        Public Property id_donnhaphang() As String
            Get
                Return fid_donnhaphang
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(id_donnhaphang), fid_donnhaphang, value)
            End Set
        End Property
        Dim ftinh_trang As String
        Public Property tinh_trang() As String
            Get
                Return ftinh_trang
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(tinh_trang), ftinh_trang, value)
            End Set
        End Property
        Dim fid_nhacungcap As String
        Public Property id_nhacungcap() As String
            Get
                Return fid_nhacungcap
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(id_nhacungcap), fid_nhacungcap, value)
            End Set
        End Property
        Dim fngayhoadon As String
        Public Property ngayhoadon() As String
            Get
                Return fngayhoadon
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(ngayhoadon), fngayhoadon, value)
            End Set
        End Property
        Dim fid_admin As String
        Public Property id_admin() As String
            Get
                Return fid_admin
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(id_admin), fid_admin, value)
            End Set
        End Property
        <Association("ChiTietDonNhapHangReferencesDonNhapHangs"), Aggregated()>
        Public ReadOnly Property ChiTietDonNhapHangs() As XPCollection(Of ChiTietDonNhapHang)
            Get
                Return GetCollection(Of ChiTietDonNhapHang)(NameOf(ChiTietDonNhapHangs))
            End Get
        End Property
    End Class

End Namespace
