'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace Demo3

    Partial Public Class SanPhams
        Inherits XPObject
        Dim fid_sanpham As String
        Public Property id_sanpham() As String
            Get
                Return fid_sanpham
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(id_sanpham), fid_sanpham, value)
            End Set
        End Property
        Dim fid_danhmuc As String
        Public Property id_danhmuc() As String
            Get
                Return fid_danhmuc
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(id_danhmuc), fid_danhmuc, value)
            End Set
        End Property
        Dim ftensanpham As String
        Public Property tensanpham() As String
            Get
                Return ftensanpham
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(tensanpham), ftensanpham, value)
            End Set
        End Property
        Dim fslug_sanpham As String
        Public Property slug_sanpham() As String
            Get
                Return fslug_sanpham
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(slug_sanpham), fslug_sanpham, value)
            End Set
        End Property
        Dim fhinhanh As String
        Public Property hinhanh() As String
            Get
                Return fhinhanh
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(hinhanh), fhinhanh, value)
            End Set
        End Property
        Dim ftinhtrang As String
        Public Property tinhtrang() As String
            Get
                Return ftinhtrang
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(tinhtrang), ftinhtrang, value)
            End Set
        End Property
        Dim fdongia As String
        Public Property dongia() As String
            Get
                Return fdongia
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(dongia), fdongia, value)
            End Set
        End Property
        Dim fgiakhuyenmai As String
        Public Property giakhuyenmai() As String
            Get
                Return fgiakhuyenmai
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(giakhuyenmai), fgiakhuyenmai, value)
            End Set
        End Property
        Dim fid_thuonghieu As String
        Public Property id_thuonghieu() As String
            Get
                Return fid_thuonghieu
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(id_thuonghieu), fid_thuonghieu, value)
            End Set
        End Property
    End Class

End Namespace
